#!/bin/bash

DIR="$HOME/.config"

rofi_command="rofi -theme $DIR/rofi/themes/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="⏻ "
reboot=" "
lock=" "
logout="󰍃 "
suspend="󰏥 "

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$logout\n$suspend"
_msg="Options  -  yes / y / no / n"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
		ans=$($HOME/.config/rofi/bin/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        systemctl poweroff
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
                exit
        fi
        ;;
    $reboot)
		ans=$($HOME/.config/rofi/bin/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        systemctl reboot
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
                exit
        fi
        ;;
    $lock)
        betterlockscreen -l blur
        ;;
    $suspend)
		ans=$($HOME/.config/rofi/bin/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        amixer set Master mute
        betterlockscreen --suspend
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
                exit
        fi
        ;;
    $logout)
		ans=$($HOME/.config/rofi/bin/confirm)
		if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        pkill -KILL -u "$USER"
		elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
        else
                exit
        fi
        ;;
esac

